apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-websocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-websocket-server
  template:
    metadata:
      labels:
        app: echo-websocket-server
    spec:
      containers:
        - name: echo-websocket-server
          image: sumeetbansal007/echo-websocket-server:6f745da
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: echo-websocket-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: echo-websocket-server
